---
javascripts:
- base:
  - jquery
  - jquery.tools.min
  - jquery-ui
  - jquery.textarea
  - jHtmlArea
  - jquery.autocomplete
  - jquery.autoSuggest
  - jquery.notifyBar
  - showdown
  - highlight/prettify
  - components/search
  - application
  - modules/sessions
  - modules/index_question
  - modules/retag
  - modules/new_question
  - modules/index_welcome
  - modules/show_user
  - modules/index_group
  - modules/index_user
  - modules/tags_question
  - modules/members
  - modules/move_group
  - modules/editor

- show:
  - jquery.autovideo
  - modules/single/question
  - modules/show_question

- login:
  - openid/js/jquery.openid.min



stylesheets:
- base:
  - jquery-ui
  - compiled/application
  - prettify
  - ../javascripts/openid/css/style

